<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

use App\Models\Country;
use App\Models\Ingredient;
use App\Models\Fact;
use App\Models\Recipe;



class FoodMapSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->truncate();
        DB::table('ingredients')->truncate();
        DB::table('facts')->truncate();
        DB::table('recipes')->truncate();


    $data = ['name' => "Grilled Chicken",
            'instruction' => "unclear, will be burned anyway",
            'image' => "beatufil_chicken.jpg",
            'isVegan' => false,
            'isVegeterian' => false,
            'isLactoseFree' => true,
            'isGlutenFree' => true,
            'isNutFree' => false,
            'country' => ["Czech republic", "cz.png"],
            'ingredients' => [[1, "whole", "chicken"], [100, "gram", "potatoes"]]];

    $countries = [ 
        "name" => "Afghanistan", "path" => "AF.png", 
        "name" => "Åland Islands", "path" => "AX.png", 
        "name" => "Albania", "path" => "AL.png", 
        "name" => "Algeria", "path" => "DZ.png", 
        "name" => "American Samoa", "path" => "AS.png", 
        "name" => "Andorra", "path" => "AD.png", 
        "name" => "Angola", "path" => "AO.png", 
        "name" => "Anguilla", "path" => "AI.png", 
        "name" => "Antarctica", "path" => "AQ.png", 
        "name" => "Antigua and Barbuda", "path" => "AG.png", 
        "name" => "Argentina", "path" => "AR.png", 
        "name" => "Armenia", "path" => "AM.png", 
        "name" => "Aruba", "path" => "AW.png", 
        "name" => "Australia", "path" => "AU.png", 
        "name" => "Austria", "path" => "AT.png", 
        "name" => "Azerbaijan", "path" => "AZ.png", 
        "name" => "Bahamas", "path" => "BS.png", 
        "name" => "Bahrain", "path" => "BH.png", 
        "name" => "Bangladesh", "path" => "BD.png", 
        "name" => "Barbados", "path" => "BB.png", 
        "name" => "Belarus", "path" => "BY.png", 
        "name" => "Belgium", "path" => "BE.png", 
        "name" => "Belize", "path" => "BZ.png", 
        "name" => "Benin", "path" => "BJ.png", 
        "name" => "Bermuda", "path" => "BM.png", 
        "name" => "Bhutan", "path" => "BT.png", 
        "name" => "Bolivia", "path" => "BO.png", 
        "name" => "Bosnia and Herzegovina", "path" => "BA.png", 
        "name" => "Botswana", "path" => "BW.png", 
        "name" => "Bouvet Island", "path" => "BV.png", 
        "name" => "Brazil", "path" => "BR.png", 
        "name" => "British Indian Ocean Territory", "path" => "IO.png", 
        "name" => "Brunei Darussalam", "path" => "BN.png", 
        "name" => "Bulgaria", "path" => "BG.png", 
        "name" => "Burkina Faso", "path" => "BF.png", 
        "name" => "Burundi", "path" => "BI.png", 
        "name" => "Cambodia", "path" => "KH.png", 
        "name" => "Cameroon", "path" => "CM.png", 
        "name" => "Canada", "path" => "CA.png", 
        "name" => "Cape Verde", "path" => "CV.png", 
        "name" => "Cayman Islands", "path" => "KY.png", 
        "name" => "Central African Republic", "path" => "CF.png", 
        "name" => "Chad", "path" => "TD.png", 
        "name" => "Chile", "path" => "CL.png", 
        "name" => "China", "path" => "CN.png", 
        "name" => "Christmas Island", "path" => "CX.png", 
        "name" => "Cocos (Keeling) Islands", "path" => "CC.png", 
        "name" => "Colombia", "path" => "CO.png", 
        "name" => "Comoros", "path" => "KM.png", 
        "name" => "Congo", "path" => "CG.png", 
        "name" => "Congo, The Democratic Republic of the", "path" => "CD.png", 
        "name" => "Cook Islands", "path" => "CK.png", 
        "name" => "Costa Rica", "path" => "CR.png", 
        "name" => "Cote D'Ivoire", "path" => "CI.png", 
        "name" => "Croatia", "path" => "HR.png", 
        "name" => "Cuba", "path" => "CU.png", 
        "name" => "Cyprus", "path" => "CY.png", 
        "name" => "Czech Republic", "path" => "CZ.png", 
        "name" => "Denmark", "path" => "DK.png", 
        "name" => "Djibouti", "path" => "DJ.png", 
        "name" => "Dominica", "path" => "DM.png", 
        "name" => "Dominican Republic", "path" => "DO.png", 
        "name" => "Ecuador", "path" => "EC.png", 
        "name" => "Egypt", "path" => "EG.png", 
        "name" => "El Salvador", "path" => "SV.png", 
        "name" => "Equatorial Guinea", "path" => "GQ.png", 
        "name" => "Eritrea", "path" => "ER.png", 
        "name" => "Estonia", "path" => "EE.png", 
        "name" => "Ethiopia", "path" => "ET.png", 
        "name" => "Falkland Islands (Malvinas)", "path" => "FK.png", 
        "name" => "Faroe Islands", "path" => "FO.png", 
        "name" => "Fiji", "path" => "FJ.png", 
        "name" => "Finland", "path" => "FI.png", 
        "name" => "France", "path" => "FR.png", 
        "name" => "French Guiana", "path" => "GF.png", 
        "name" => "French Polynesia", "path" => "PF.png", 
        "name" => "French Southern Territories", "path" => "TF.png", 
        "name" => "Gabon", "path" => "GA.png", 
        "name" => "Gambia", "path" => "GM.png", 
        "name" => "Georgia", "path" => "GE.png", 
        "name" => "Germany", "path" => "DE.png", 
        "name" => "Ghana", "path" => "GH.png", 
        "name" => "Gibraltar", "path" => "GI.png", 
        "name" => "Greece", "path" => "GR.png", 
        "name" => "Greenland", "path" => "GL.png", 
        "name" => "Grenada", "path" => "GD.png", 
        "name" => "Guadeloupe", "path" => "GP.png", 
        "name" => "Guam", "path" => "GU.png", 
        "name" => "Guatemala", "path" => "GT.png", 
        "name" => "Guernsey", "path" => "GG.png", 
        "name" => "Guinea", "path" => "GN.png", 
        "name" => "Guinea-Bissau", "path" => "GW.png", 
        "name" => "Guyana", "path" => "GY.png", 
        "name" => "Haiti", "path" => "HT.png", 
        "name" => "Heard Island and Mcdonald Islands", "path" => "HM.png", 
        "name" => "Holy See (Vatican City State)", "path" => "VA.png", 
        "name" => "Honduras", "path" => "HN.png", 
        "name" => "Hong Kong", "path" => "HK.png", 
        "name" => "Hungary", "path" => "HU.png", 
        "name" => "Iceland", "path" => "IS.png", 
        "name" => "India", "path" => "IN.png", 
        "name" => "Indonesia", "path" => "ID.png", 
        "name" => "Iran, Islamic Republic Of", "path" => "IR.png", 
        "name" => "Iraq", "path" => "IQ.png", 
        "name" => "Ireland", "path" => "IE.png", 
        "name" => "Isle of Man", "path" => "IM.png", 
        "name" => "Israel", "path" => "IL.png", 
        "name" => "Italy", "path" => "IT.png", 
        "name" => "Jamaica", "path" => "JM.png", 
        "name" => "Japan", "path" => "JP.png", 
        "name" => "Jersey", "path" => "JE.png", 
        "name" => "Jordan", "path" => "JO.png", 
        "name" => "Kazakhstan", "path" => "KZ.png", 
        "name" => "Kenya", "path" => "KE.png", 
        "name" => "Kiribati", "path" => "KI.png", 
        "name" => "Korea, Democratic People'S Republic of", "path" => "KP.png", 
        "name" => "Korea, Republic of", "path" => "KR.png", 
        "name" => "Kuwait", "path" => "KW.png", 
        "name" => "Kyrgyzstan", "path" => "KG.png", 
        "name" => "Lao People'S Democratic Republic", "path" => "LA.png", 
        "name" => "Latvia", "path" => "LV.png", 
        "name" => "Lebanon", "path" => "LB.png", 
        "name" => "Lesotho", "path" => "LS.png", 
        "name" => "Liberia", "path" => "LR.png", 
        "name" => "Libyan Arab Jamahiriya", "path" => "LY.png", 
        "name" => "Liechtenstein", "path" => "LI.png", 
        "name" => "Lithuania", "path" => "LT.png", 
        "name" => "Luxembourg", "path" => "LU.png", 
        "name" => "Macao", "path" => "MO.png", 
        "name" => "Macedonia, The Former Yugoslav Republic of", "path" => "MK.png", 
        "name" => "Madagascar", "path" => "MG.png", 
        "name" => "Malawi", "path" => "MW.png", 
        "name" => "Malaysia", "path" => "MY.png", 
        "name" => "Maldives", "path" => "MV.png", 
        "name" => "Mali", "path" => "ML.png", 
        "name" => "Malta", "path" => "MT.png", 
        "name" => "Marshall Islands", "path" => "MH.png", 
        "name" => "Martinique", "path" => "MQ.png", 
        "name" => "Mauritania", "path" => "MR.png", 
        "name" => "Mauritius", "path" => "MU.png", 
        "name" => "Mayotte", "path" => "YT.png", 
        "name" => "Mexico", "path" => "MX.png", 
        "name" => "Micronesia, Federated States of", "path" => "FM.png", 
        "name" => "Moldova, Republic of", "path" => "MD.png", 
        "name" => "Monaco", "path" => "MC.png", 
        "name" => "Mongolia", "path" => "MN.png", 
        "name" => "Montenegro", "path" => "ME.png",
        "name" => "Montserrat", "path" => "MS.png",
        "name" => "Morocco", "path" => "MA.png", 
        "name" => "Mozambique", "path" => "MZ.png", 
        "name" => "Myanmar", "path" => "MM.png", 
        "name" => "Namibia", "path" => "NA.png", 
        "name" => "Nauru", "path" => "NR.png", 
        "name" => "Nepal", "path" => "NP.png", 
        "name" => "Netherlands", "path" => "NL.png", 
        "name" => "Netherlands Antilles", "path" => "AN.png", 
        "name" => "New Caledonia", "path" => "NC.png", 
        "name" => "New Zealand", "path" => "NZ.png", 
        "name" => "Nicaragua", "path" => "NI.png", 
        "name" => "Niger", "path" => "NE.png", 
        "name" => "Nigeria", "path" => "NG.png", 
        "name" => "Niue", "path" => "NU.png", 
        "name" => "Norfolk Island", "path" => "NF.png", 
        "name" => "Northern Mariana Islands", "path" => "MP.png", 
        "name" => "Norway", "path" => "NO.png", 
        "name" => "Oman", "path" => "OM.png", 
        "name" => "Pakistan", "path" => "PK.png", 
        "name" => "Palau", "path" => "PW.png", 
        "name" => "Palestinian Territory, Occupied", "path" => "PS.png", 
        "name" => "Panama", "path" => "PA.png", 
        "name" => "Papua New Guinea", "path" => "PG.png", 
        "name" => "Paraguay", "path" => "PY.png", 
        "name" => "Peru", "path" => "PE.png", 
        "name" => "Philippines", "path" => "PH.png", 
        "name" => "Pitcairn", "path" => "PN.png", 
        "name" => "Poland", "path" => "PL.png", 
        "name" => "Portugal", "path" => "PT.png", 
        "name" => "Puerto Rico", "path" => "PR.png", 
        "name" => "Qatar", "path" => "QA.png", 
        "name" => "Reunion", "path" => "RE.png", 
        "name" => "Romania", "path" => "RO.png", 
        "name" => "Russian Federation", "path" => "RU.png", 
        "name" => "RWANDA", "path" => "RW.png", 
        "name" => "Saint Helena", "path" => "SH.png", 
        "name" => "Saint Kitts and Nevis", "path" => "KN.png", 
        "name" => "Saint Lucia", "path" => "LC.png", 
        "name" => "Saint Pierre and Miquelon", "path" => "PM.png", 
        "name" => "Saint Vincent and the Grenadines", "path" => "VC.png", 
        "name" => "Samoa", "path" => "WS.png", 
        "name" => "San Marino", "path" => "SM.png", 
        "name" => "Sao Tome and Principe", "path" => "ST.png", 
        "name" => "Saudi Arabia", "path" => "SA.png", 
        "name" => "Senegal", "path" => "SN.png", 
        "name" => "Serbia", "path" => "RS.png", 
        "name" => "Seychelles", "path" => "SC.png", 
        "name" => "Sierra Leone", "path" => "SL.png", 
        "name" => "Singapore", "path" => "SG.png", 
        "name" => "Slovakia", "path" => "SK.png", 
        "name" => "Slovenia", "path" => "SI.png", 
        "name" => "Solomon Islands", "path" => "SB.png", 
        "name" => "Somalia", "path" => "SO.png", 
        "name" => "South Africa", "path" => "ZA.png", 
        "name" => "South Georgia and the South Sandwich Islands", "path" => "GS.png", 
        "name" => "Spain", "path" => "ES.png", 
        "name" => "Sri Lanka", "path" => "LK.png", 
        "name" => "Sudan", "path" => "SD.png", 
        "name" => "Suriname", "path" => "SR.png", 
        "name" => "Svalbard and Jan Mayen", "path" => "SJ.png", 
        "name" => "Swaziland", "path" => "SZ.png", 
        "name" => "Sweden", "path" => "SE.png", 
        "name" => "Switzerland", "path" => "CH.png", 
        "name" => "Syrian Arab Republic", "path" => "SY.png", 
        "name" => "Taiwan, Province of China", "path" => "TW.png", 
        "name" => "Tajikistan", "path" => "TJ.png", 
        "name" => "Tanzania, United Republic of", "path" => "TZ.png", 
        "name" => "Thailand", "path" => "TH.png", 
        "name" => "Timor-Leste", "path" => "TL.png", 
        "name" => "Togo", "path" => "TG.png", 
        "name" => "Tokelau", "path" => "TK.png", 
        "name" => "Tonga", "path" => "TO.png", 
        "name" => "Trinidad and Tobago", "path" => "TT.png", 
        "name" => "Tunisia", "path" => "TN.png", 
        "name" => "Turkey", "path" => "TR.png", 
        "name" => "Turkmenistan", "path" => "TM.png", 
        "name" => "Turks and Caicos Islands", "path" => "TC.png", 
        "name" => "Tuvalu", "path" => "TV.png", 
        "name" => "Uganda", "path" => "UG.png", 
        "name" => "Ukraine", "path" => "UA.png", 
        "name" => "United Arab Emirates", "path" => "AE.png", 
        "name" => "United Kingdom", "path" => "GB.png", 
        "name" => "United States", "path" => "US.png", 
        "name" => "United States Minor Outlying Islands", "path" => "UM.png", 
        "name" => "Uruguay", "path" => "UY.png", 
        "name" => "Uzbekistan", "path" => "UZ.png", 
        "name" => "Vanuatu", "path" => "VU.png", 
        "name" => "Venezuela", "path" => "VE.png", 
        "name" => "Viet Nam", "path" => "VN.png", 
        "name" => "Virgin Islands, British", "path" => "VG.png", 
        "name" => "Virgin Islands, U.S.", "path" => "VI.png", 
        "name" => "Wallis and Futuna", "path" => "WF.png", 
        "name" => "Western Sahara", "path" => "EH.png", 
        "name" => "Yemen", "path" => "YE.png", 
        "name" => "Zambia", "path" => "ZM.png", 
        "name" => "Zimbabwe", "path" => "ZW.png" 
    ];
}
}